name: battery_monitor
description: Aplicativo Flutter que monitora o nível de bateria do dispositivo e alerta quando estiver abaixo de 20%.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  battery_plus: ^4.0.0 # ou a versão mais recente
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true